name: CI
concurrency: ${{ github.workflow }}-${{ github.ref }}

on: push

jobs:
  Functional_Test:
    name: Functional Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3          
      
      - name: Display result 1
        run: find ./src/layouts -type f -name "*.js.gz"
      
      - name: Display result 2
        run: find ./src/layouts -type f -name "*.js.gz"          

       