# name: CI
# concurrency: ${{ github.workflow }}-${{ github.ref }}

# on: push

# jobs:
#   ci:
#     timeout-minutes: 10
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           persist-credentials: false
      
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version-file: .nvmrc
#           always-auth: true
#           cache: npm
#           registry-url: https://registry.npmjs.org
      
#       - name: Install dependencies
#         run: npm ci --ignore-scripts
    
#   call-workflow:
#     uses: ./.github/workflows/ci2.yml


name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value