name: CI2
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install dependencies
        run: npm ci --ignore-scripts